Repository Team-Teamble/Teamble-Server, pull requests merged in 2022-03, with the labels that each got.

#84 [REFACTOR] initial foldering
  v2/.eslintrc.js
  v2/.prettierrc.js
  v2/package.json
  v2/src/app.ts
  v2/src/constants/responseMessage.ts
  v2/src/constants/statusCode.ts
  v2/src/endpoint/index.ts
  v2/src/endpoint/project.ts
  v2/src/endpoint/user.ts
  v2/src/entity/project.ts
  v2/src/entity/user.ts
  v2/src/index.ts
  v2/src/lib/endpoint.ts
  v2/src/lib/printer.ts
  v2/src/lib/util.ts
  v2/src/repository/index.ts
  v2/src/repository/localStorageRepository.ts
  v2/yarn.lock
Labels: settings

#85 [CORRECT] js to ts
  v2/src/constants/responseMessage.ts
  v2/src/constants/statusCode.ts
  v2/src/lib/util.ts
Labels: bug

#88 [FEAT] first api test
  v2/package.json
  v2/src/endpoint/user.ts
  v2/src/entity/user.ts
  v2/src/repository/index.ts
  v2/src/repository/localStorageRepository.ts
  v2/yarn.lock
Labels: 💜API, 🌻Gyuwon

#89 [FEAT] first api test - project
  v2/src/endpoint/project.ts
  v2/src/entity/project.ts
  v2/src/repository/index.ts
  v2/src/repository/localStorageRepository.ts
Labels: 💜API, 🌷Hyeonji
