Repository Team-Teamble/Teamble-Server, pull requests merged in 2022-05, with the labels that each got.

#93 [FEAT] structured foldering & swagger setting
  v2/package.json
  v2/src/app.ts
  v2/src/config/db.ts
  v2/src/controllers/UserController.ts
  v2/src/controllers/index.ts
  v2/src/endpoint/index.ts
  v2/src/endpoint/user2.ts
  v2/src/interfaces/Project.ts
  v2/src/interfaces/user/User.ts
  v2/src/interfaces/user/UserCreateDto.ts
  v2/src/legacy/endpoint/index.ts
  v2/src/legacy/endpoint/project.ts
  v2/src/legacy/endpoint/user.ts
  v2/src/legacy/endpoint/user2.ts
  v2/src/legacy/repository/index.ts
  v2/src/legacy/repository/localStorageRepository.ts
  v2/src/legacy/repository/mysqlRepository.ts
  v2/src/repository/db.ts
  v2/src/routes/UserRouter.ts
  v2/src/routes/index.ts
  v2/src/services/UserService.ts
  v2/src/services/index.ts
  v2/src/swagger/openapi.yaml
  v2/src/swagger/paths/_index.yaml
  v2/yarn.lock
Labels: 🌷Hyeonji, settings

#92 [ADD] basic setting of aws s3
  v2/.gitignore
  v2/package.json
  v2/src/config/db.ts
  v2/src/legacy/endpoint/project.ts
  v2/src/legacy/endpoint/user.ts
  v2/src/legacy/endpoint/user2.ts
  v2/src/legacy/repository/index.ts
  v2/src/legacy/repository/mysqlRepository.ts
  v2/src/lib/imageUpload.ts
  v2/yarn.lock
Labels: 🌻Gyuwon, settings

#94 [ADD] swagger example
  v2/package.json
  v2/src/legacy/endpoint/project.ts
  v2/src/legacy/endpoint/user.ts
  v2/src/swagger/openapi.yaml
Labels: 🌷Hyeonji, settings

#95 [#TB-116] Swagger Refactor
  v2/src/swagger/examples/_index.yaml
  v2/src/swagger/examples/field.yaml
  v2/src/swagger/examples/fieldWithoutAll.yaml
  v2/src/swagger/examples/projectCard.yaml
  v2/src/swagger/openapi.yaml
  v2/src/swagger/parameters/_index.yaml
  v2/src/swagger/parameters/userId.yaml
  v2/src/swagger/parameters/xAuthorizationToken.yaml
  v2/src/swagger/paths/_index.yaml
  v2/src/swagger/paths/auth/authSignup.yaml
  v2/src/swagger/paths/auth/authSignupMetadata.yaml
  v2/src/swagger/paths/common.yaml
  v2/src/swagger/paths/project/projectTop.yaml
  v2/src/swagger/paths/user/userProfileUserId.yaml
  v2/src/swagger/requestBodies/_index.yaml
  v2/src/swagger/responses/400-FileTypeError.yaml
  v2/src/swagger/responses/400-NullValue.yaml
  v2/src/swagger/responses/400-OutofValue.yaml
  v2/src/swagger/responses/401-TokenEmpty.yaml
  v2/src/swagger/responses/401-TokenInvalid.yaml
  v2/src/swagger/responses/404-NoUser.yaml
  v2/src/swagger/responses/404-NotFound.yaml
  v2/src/swagger/responses/500-InternalServerError.yaml
  v2/src/swagger/responses/_index.yaml
  v2/src/swagger/schemas/Fail.yaml
  v2/src/swagger/schemas/Success.yaml
  v2/src/swagger/schemas/User.yaml
  v2/src/swagger/schemas/_index.yaml
Labels: documentation, 🌻Gyuwon
